name: &name "MultiscaleDiarDecoder"
sample_rate: &sample_rate 16000
repeat: &rep 2
dropout: &drop 0.5
separable: &separable True
n_filters: &n_filters 256
num_workers: &num_workers 20
batch_size: &global_bs 512

diarizer: &diarizer
  manifest_filepath: null
  out_dir: null
  oracle_vad: True # If True, uses RTTM files provided in manifest file to get speech activity (VAD) timestamps
  collar: 0.25 # Collar value for scoring
  ignore_overlap: True # Consider or ignore overlap segments while scoring

  vad:
    model_path: null # .nemo local model path or pretrained model name or none
    external_vad_manifest: null # This option is provided to use external vad and provide its speech activity labels for speaker embeddings extraction. Only one of model_path or external_vad_manifest should be set

    parameters: # Tuned parameter for CH109 (using the 11 multi-speaker sessions as dev set) 
      window_length_in_sec: 0.15  # Window length in sec for VAD context input 
      shift_length_in_sec: 0.01 # Shift length in sec for generate frame level VAD prediction
      smoothing: "median" # False or type of smoothing method (eg: median)
      overlap: 0.875 # Overlap ratio for overlapped mean/median smoothing filter
      onset: 0.4 # Onset threshold for detecting the beginning and end of a speech 
      offset: 0.7 # Offset threshold for detecting the end of a speech
      pad_onset: 0.05 # Adding durations before each speech segment 
      pad_offset: -0.1 # Adding durations after each speech segment 
      min_duration_on: 0.2 # Threshold for small non_speech deletion
      min_duration_off: 0.2 # Threshold for short speech segment deletion
      filter_speech_first: True 

  speaker_embeddings:
    model_path: "/home/taejinp/Downloads/titanet-m.nemo"  # .nemo local model path or pretrained model name (titanet_large, ecapa_tdnn or speakerverification_speakernet)
    parameters:
      window_length_in_sec: [1.5,1.25,1.0,0.75,0.5] # Window length(s) in sec (floating-point number). Either a number or a list. Ex) 1.5 or [1.5,1.0,0.5]
      shift_length_in_sec: [0.75,0.625,0.5,0.375,0.25] # Shift length(s) in sec (floating-point number). Either a number or a list. Ex) 0.75 or [0.75,0.5,0.25]
      multiscale_weights: [0.05,0.2875,0.525,0.7625,1.0] # CH109 opt
      save_embeddings: True # Save embeddings as pickle file for each audio input.
  
  clustering:
    parameters:
      oracle_num_speakers: False  # If True, use num of speakers value provided in manifest file.
      max_num_speakers: &max_num_speakers 8 # Max number of speakers for each recording. If oracle num speakers is passed, this value is ignored.
      enhanced_count_thres: 80 # If the number of segments is lower than this number, enhanced speaker counting is activated.
      max_rp_threshold: 0.15 # Determines the range of p-value search: 0 < p <= max_rp_threshold. 
      sparse_search_volume: 30 # The higher the number, the more values will be examined with more time. 

  msdd_model:
    model_path: null
    parameters:
      run_clus_from_loaded_emb: True
      use_single_scale_clustering: True
      infer_batch_size: &infer_batch_size 100
      sigmoid_threshold: [0.85,0.97]
      seq_eval_mode: True
      #sigmoid_threshold: [0.5,0.55,0.6,0.65,0.7,0.75,0.8,0.85,0.9,0.97]
      #sigmoid_threshold: [0.80,0.81,0.82,0.83,0.84,0.85,0.86,0.87,0.88,0.89,0.90,0.91,0.92,0.93,0.94,0.95]
      #sigmoid_threshold: [0.91,0.92,0.93,0.94,0.95,0.96,0.97,0.98,0.99]
      

msdd_model: 
  base:
    name: *name 
    sample_rate: *sample_rate
    repeat: *rep
    dropout: *drop
    separable: *separable
    n_filters: *n_filters
    num_workers: *num_workers
    batch_size: *global_bs
    diarizer: *diarizer
    soft_label_thres: &soft_label_thres 0.5
  max_num_of_spks: *max_num_speakers
  scale_n: &scale_n 5
  subsample_rate: &subsample_rate 1
  split_length: 30
  emb_batch_size: 100
  use_longest_scale_clus_avg_emb: True
  weighting_scheme: "corr"
  #weighting_scheme: "conv"
  
  test_ds:
    manifest_filepath: null
    emb_dir: null
    sample_rate: 16000
    num_spks: 2
    soft_label_thres: *soft_label_thres
    labels: null
    batch_size: *infer_batch_size
    shuffle: False

  preprocessor:
    _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
    normalize: "per_feature"
    window_size: 0.02
    sample_rate: *sample_rate
    window_stride: 0.01
    window: "hann"
    features: &n_mels 64
    n_fft: 512
    frame_splicing: 1
    dither: 0.00001
  
  msdd_module:
    _target_: nemo.collections.asr.modules.msdd_diarizer.MSDD_module
    num_spks: 2
    hidden_size: 256
    dropout_rate: 0.5
    cnn_output_ch: 4
    emb_sizes: 192
    scale_n: *scale_n

