name: G2PClassification

# Dataset info
train_dataset: ???
validation_dataset: ???
do_testing: False
pretrained_model: null # .nemo

model:
  model_name: byt5
  max_sequence_len: 512

  encoder:
    pretrained: null # pretrained g2p model with encoder
    transformer: bert-base-cased #google/byt5-small
    dropout: null

  tokenizer_grapheme:
    pretrained: ${model.encoder.transformer}
    grapheme_unk_token: "Ò‚"
    vocab_file: null # will be filled during training

#  classifier_head:
#    num_output_layers: 2
#    fc_dropout: 0.1

  head:
    num_fc_layers: 2
    fc_dropout: 0.5
    activation: 'relu'
    use_transformer_init: True

  train_ds:
    dataset:
      _target_: "nemo.collections.tts.torch.data.T5G2PDataset"
      data_dir: ${train_dataset}
      wordids: "/home/ebakhturina/g2p_scripts/WikipediaHomographData-master/data/wordids.tsv"
      context_len: 5
    dataloader_params:
      drop_last: false
      shuffle: true
      batch_size: 32
      num_workers: 0

  validation_ds:
    dataset:
      #_target_: "nemo.collections.tts.data.datalayers.T5G2PDataset"
      data_dir: ${validation_dataset}
      context_len: 5
    dataloader_params:
      drop_last: false
      shuffle: false
      batch_size: 32
      num_workers: 0

  test_ds:
    dataset:
      #_target_: "nemo.collections.tts.data.datalayers.T5G2PDataset"
      data_dir: null
      context_len: 5
    dataloader_params:
      drop_last: false
      shuffle: false
      batch_size: 32 #64
      num_workers: 0

  optim:
    name: adamw
    lr: 5e-5
    weight_decay: 0.01
    # scheduler setup
    sched:
      name: WarmupAnnealing
      # pytorch lightning args
      reduce_on_plateau: false
      # scheduler config override
      warmup_steps: null
      warmup_ratio: 0.1
      last_epoch: -1

trainer:
  devices: 1 # number of gpus
  max_epochs: 10
  num_nodes: 1
  accelerator: gpu
  strategy: ddp
  accumulate_grad_batches: 1
  enable_checkpointing: False  # Provided by exp_manager
  logger: False  # Provided by exp_manager
  log_every_n_steps: 200
  check_val_every_n_epoch: 1

exp_manager:
  exp_dir: null
  name: ${name}
  create_tensorboard_logger: True
  create_checkpoint_callback: True
  checkpoint_callback_params:
    save_top_k: 3
    monitor: "val_loss"
    mode: "min"
    save_best_model: true
  create_wandb_logger: true
  wandb_logger_kwargs:
    project: g2p_classification
    name: "token_cl_with_mask"

