name: "VITS"

labels: [' ', '!', "'", '(', ')', ',', '-', '.', ':', ';', '?', 'a', 'b', 'c', 'd', 'e', 'f', 'g',
         'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
train_dataset: ???
validation_datasets: ???
test_datasets: null

model:
  sample_rate: 22050
  splice_length: 64
  lr: 2e-4
  labels: ${labels}
  n_speakers: 1
  symbols_embedding_dim: 384
  max_token_duration: 75
  n_mel_channels: 80
  pitch_embedding_kernel_size: 3
  mel_loss_coeff: 40
  hop_size: 256
  log_interval: 200
  eval_interval: 1000
  seed: 1234
  betas: [0.8,0.99]
  eps: 1e-9
  lr_decay: 0.999875
  segment_size: 8192
  init_lr_ratio: 1
  warmup_epochs: 0
  c_mel: 45
  c_kl: 1.
  inter_channels: 192
  hidden_channels: 192
  filter_channels: 768
  n_heads: 2
  p_dropout: 0.1
  n_layers_q: 3
  use_spectral_norm: false
  mel_fmin: 0.0
  mel_fmax: null

  train_ds:
    manifest_filepath: ${train_dataset}
    max_duration: null
    min_duration: 0.1
    sample_rate: ${model.sample_rate}
    trim: false
    parser: null
    drop_last: true
    shuffle: true
    batch_size: 64
    num_workers: 12
    max_wav_value: 32768.0
    filter_length: 1024

  validation_ds:
    manifest_filepath: ${validation_datasets}
    sample_rate: ${model.sample_rate}
    trim: false
    parser: null
    drop_last: false
    shuffle: false
    batch_size: 64
    num_workers: 8
    max_wav_value: 32768.0
    filter_length: 1024

  preprocessor:
    _target_: nemo.collections.asr.parts.preprocessing.features.FilterbankFeatures
    dither: 0.0
    nfilt: ${model.n_mel_channels}
    frame_splicing: 1
    highfreq: 8000
    log: true
    log_zero_guard_type: clamp
    log_zero_guard_value: 1e-05
    lowfreq: 0
    mag_power: 1.0
    n_fft: 1024
    n_window_size: 1024
    n_window_stride: ${model.hop_size}
    normalize: null
    pad_to: 1
    pad_value: 0
    preemph: null
    sample_rate: ${model.sample_rate}
    window: hann
    exact_pad: true
    use_grads: false

  input_fft:
    _target_: nemo.collections.tts.modules.transformer.FFTransformerEncoder
    n_layer: 6
    n_head: 1
    d_model: ${model.symbols_embedding_dim}
    d_head: 64
    d_inner: 1536
    kernel_size: 3
    dropout: 0.1
    dropatt: 0.1
    dropemb: 0.0
    n_embed: 148  # NOTE Should match # of tokens in `symbol_set`
    d_embed: ${model.symbols_embedding_dim}
    padding_idx: 0

  output_fft:
    _target_: nemo.collections.tts.modules.transformer.FFTransformerDecoder
    n_layer: 6
    n_head: 1
    d_model: ${model.symbols_embedding_dim}
    d_head: 64
    d_inner: 1536
    kernel_size: 3
    dropout: 0.1
    dropatt: 0.1
    dropemb: 0.0

  duration_predictor:
    _target_: nemo.collections.tts.modules.vits_modules.StochasticDurationPredictor
    input_size: ${model.symbols_embedding_dim}
    kernel_size: 3
    filter_size: 256
    dropout: 0.1
    n_layers: 6

  pitch_predictor:
    _target_: nemo.collections.tts.modules.fastpitch.TemporalPredictor
    input_size: ${model.symbols_embedding_dim}
    kernel_size: 3
    filter_size: 256
    dropout: 0.1
    n_layers: 6

  generator:
    _target_: nemo.collections.tts.modules.vits_modules.Generator
    resblock: 1
    resblock_kernel_sizes: [3,7,11]
    resblock_dilation_sizes: [[1,3,5], [1,3,5], [1,3,5]]
    upsample_rates: [8,8,2,2]
    upsample_initial_channel: 512
    upsample_kernel_sizes: [16,16,4,4]
    initial_input_size: 384

trainer:
  gpus: -1 # number of gpus
  max_epochs: 20000
  num_nodes: 1
  accelerator: ddp
  accumulate_grad_batches: 1
  checkpoint_callback: False  # Provided by exp_manager
  logger: False  # Provided by exp_manager
  gradient_clip_val: 1000.0
  flush_logs_every_n_steps: 1000
  log_every_n_steps: 100
  check_val_every_n_epoch: 5
  precision: 16

exp_manager:
  exp_dir: null
  name: ${name}
  create_tensorboard_logger: True
  create_checkpoint_callback: True
