# Set the required transforms.
transforms:
  - # ResNet50 requires 3 x 224 x 224
    _target_: torchvision.transforms.Resize
    size: [224, 224] # [H, W]
  - # To Tensor
    _target_: torchvision.transforms.ToTensor
  - # Standard ImageNet normalization
    _target_: torchvision.transforms.Normalize
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
      
# Overwrite the dataloader settings.
dataloader:
  batch_size: 64
  num_workers: 5

# Overwrite the optimzer settins.
optim:
  lr: 0.001

# Model settings.
model:
  backbone_type: "resnet50"
  output_size: 10
  pretrained: True


# Overwrite the "trainer" settings: use 2 GPUs.
trainer:
  gpus: 2
  distributed_backend: "dp"
