# Overwrite "model" settings.
model: 
  training:
    dataset:
      params:
        # LeNet-5 accepts images of size 32x32
        width: 32
        height: 32
    dataloader:
      params:
        batch_size: 64
  optim:
    params:
      lr: 0.01

# Overwrite "trainer" settings: use 2 GPUs.
trainer:
  gpus: 2
  distributed_backend: "dp"
