# Overwrite model settings.
model: 
  module: # empty
  training:
    dataloader:
      params:
        batch_size: 64
  opt:
    params:
      lr: 0.02
    

# Overwrite trainer settings.
trainer:
  gpus: 2
  distributed_backend: "dp"

