# Overwrite the dataloader settings.
dataloader:
  batch_size: 2
  num_workers: 0

train_dataset:
  # Significantly fastens data fetching - useful for text-only based models.
  stream_images: False
  split: "validation"
  download: False # Got the proper data - turning this off, as md5 validation is slow.

# Set the required transforms.
model:
  question_transforms:
    - # Remove punctuation
      _target_: nemo.collections.vis.transforms.RemovePunctuation
    - # Lowercase
      _target_: nemo.collections.vis.transforms.LowerCase
    - # Tokenize
      _target_: nemo.collections.vis.transforms.Tokenizer
  answer_transforms:
    - # To index
      _target_: nemo.collections.vis.transforms.WordToIndex
      word_mappings_filepath: "~/data/clevr/answers_word_mappings.csv"
    - # To tensor
      _target_: nemo.collections.vis.transforms.ToTensor
  
  embeddings:
    word_mappings_filepath: "~/data/clevr/questions_word_mappings.csv"
    embeddings_size: 50
    additional_tokens: ['<PAD>']
    #pretrained_embeddings: "glove.6B.50d.txt"
    

# Overwrite the optimzer settins.
optim:
  lr: 0.01

# Overwrite the "trainer" settings: use 2 GPUs.
trainer:
  gpus: 0
  distributed_backend: "dp"
