# Overwrite the dataloader settings.
dataloader:
  batch_size: 64
  num_workers: 5

train_dataset:
  # Significantly fastens data fetching - useful for text-only based models.
  stream_images: False
  split: "train"
  download: False # Got the proper data - turning this off, as md5 validation is slow.

# Set the required transforms.
model:
  text_transforms:
    - # Remove punctuation
      _target_: nemo.collections.vis.transforms.RemovePunctuation
    - # Remove characters
      _target_: nemo.collections.vis.transforms.RemoveCharacters
      characters_to_remove: ["ą","ę"]
    - # Tokenize
      _target_: nemo.collections.vis.transforms.Tokenizer


# Overwrite the optimzer settins.
optim:
  lr: 0.01

# Overwrite the "trainer" settings: use 2 GPUs.
trainer:
  gpus: 2
  distributed_backend: "dp"
