# Overwrite the dataloader settings.
dataloader:
  batch_size: 64
  num_workers: 5

  # Set the required transforms.
transforms:
  - # To tensor
    _target_: torchvision.transforms.ToTensor


train_dataset:
  # Significantly fastens data fetching - useful for text-only based models.
  stream_images: False
  split: "validation"
  download: False # Got the proper data - turning this off, as md5 validation is slow.


# Overwrite the optimzer settins.
optim:
  lr: 0.01

# Overwrite the "trainer" settings: use 2 GPUs.
trainer:
  gpus: 2
  distributed_backend: "dp"
