# Overwrite the dataloader settings.
dataloader:
  batch_size: 64
  num_workers: 5

training_dataset:
  download: False # Got the proper data - turning this off, as md5 validation is slow.
  stream_images: False

validation_dataset:
  download: False # Got the proper data - turning this off, as md5 validation is slow.
  stream_images: False
    
question_text_transforms:
  - # Remove punctuation
    _target_: nemo.collections.vis.transforms.RemovePunctuation
  - # Lowercase
    _target_: nemo.collections.vis.transforms.LowerCase
  - # Tokenize
    _target_: nemo.collections.vis.transforms.Tokenizer

question_word_mappings_filepath: "~/data/clevr/questions_word_mappings.csv"
answers_word_mappings_filepath: "~/data/clevr/answers_word_mappings.csv"
