name: megatron_t0_prime

trainer:
  gpus: 2
  num_nodes: 1
  accelerator: gpu
  precision: 16
  logger: False # logger provided by exp_manager
  checkpoint_callback: False
  replace_sampler_ddp: False
  max_epochs: 30
  max_steps: null # consumed_samples = global_step * micro_batch_size * data_parallel_size * accumulate_grad_batches
  log_every_n_steps: 100
  val_check_interval: 1.0
  accumulate_grad_batches: 4
  gradient_clip_val: 1.0

exp_manager:
  explicit_log_dir: null
  exp_dir: null  #TODO: does this allow me to specify which dict to save to
  name: megatron_t0_prime
  create_wandb_logger: False
  wandb_logger_kwargs:
    project: null
    name: null
  resume_if_exists: True
  resume_ignore_no_checkpoint: True
  create_checkpoint_callback: True
  checkpoint_callback_params:
    monitor: val_acc
    save_top_k: 1
    mode: max
    always_save_nemo: False # TODO: add support
    filename: 'megatron_t0_prime--{val_acc:.3f}-{step}'
    model_parallel_size: ${model.tensor_model_parallel_size}
    save_best_model: True

model:
  seed: 1234
  restore_from_path: /home/jpilault/models/megatron_t5/t5_220m/megatron_t5--val_loss=1.47-step=999999-consumed_samples=2047944704.0.nemo
  tensor_model_parallel_size: 2
  pipeline_model_parallel_size: 1 # T5 PP is not supported yet. Use 1 for now.
  gradient_as_bucket_view: True # Allocate gradients in a contiguous bucket to save memory (less fragmentation and buffer memory)
  megatron_amp_O2: False # Enable O2 optimization for megatron amp

  freeze: False
  pseudo_token: '[PROMPT]' # pseudo prompt tokens
  hidden_dropout: 0.0
  attention_dropout: 0.0

  prompt_encoder:
    seq_len: 96
    dropout: 0.0
    num_layers: 2
    reparametrize: True
    task_dependent: True
    prompt_gen_type: linear

  data:
    dir_path: '/home/jpilault/datasets/T0_prompted'
    max_sampling_size: 500000  # from T0 paper (https://arxiv.org/abs/2110.08207)
    num_workers: 24
    num_data_shards: 1
    train_ds:
      batch_size: 8
      shuffle: True
      pin_memory: True
      max_seq_length: 512

    validation_ds:
      batch_size: 16
      shuffle: False
      pin_memory: True
      max_seq_length: 512

    test_ds:
      batch_size: 16
      shuffle: False
      pin_memory: True
      max_seq_length: 512

  optim:
    name: fused_adam
    lr: 1e-4
    weight_decay: 0.0
