name: megatron_t0_prime

trainer:
  gpus: 1
  num_nodes: 1
  accelerator: ddp
  precision: 16
  logger: False # logger provided by exp_manager
  checkpoint_callback: False
  replace_sampler_ddp: False
  max_epochs: 1
  max_steps: null # consumed_samples = global_step * micro_batch_size * data_parallel_size * accumulate_grad_batches
  log_every_n_steps: 10
  val_check_interval: 1
  accumulate_grad_batches: 2
  gradient_clip_val: 1.0

exp_manager:
  explicit_log_dir: null
  exp_dir: null  #TODO: does this allow me to specify which dict to save to
  name: megatron_t0
  create_wandb_logger: False
  wandb_logger_kwargs:
    project: null
    name: null
  resume_if_exists: True
  resume_ignore_no_checkpoint: True
  create_checkpoint_callback: True
  checkpoint_callback_params:
    monitor: val_acc
    save_top_k: 10
    mode: max
    always_save_nemo: False # TODO: add support
    filename: 'megatron_t0_prime--{val_acc:.3f}-{step}'
    model_parallel_size: ${model.tensor_model_parallel_size}
    save_best_model: True

model:
  seed: 1234
  restore_from_path: /home/jpilault/models/megatron_t5/t5_220m/megatron_t5--val_loss=1.54-step=415999-consumed_samples=851965952.0.nemo
  tensor_model_parallel_size: 1
  pseudo_token: '[PROMPT]' # pseudo prompt tokens
  freeze: True

  prompt_encoder:
    seq_len: 96
    dropout: 0.0
    num_layers: 2
    reparametrize: True
    task_dependent: True
    prompt_gen_type: linear

  data:
    dir_path: '/home/jpilault/datasets/T0_prompted'
    max_data_size: 500000  # from T0 paper (https://arxiv.org/abs/2110.08207)
    train_ds:
      batch_size: 16
      shuffle: True
      num_workers: 0
      pin_memory: True
      max_seq_length: 416

    validation_ds:
      batch_size: 32
      shuffle: False
      num_workers: 0
      pin_memory: True
      max_seq_length: 416

    test_ds:
      batch_size: 32
      shuffle: False
      num_workers: 0
      pin_memory: True
      max_seq_length: 416

  optim:
    name: fused_adam
    lr: 5e-6
    weight_decay: 0.0
    sched:
      name: WarmupAnnealing
      # Scheduler params
      warmup_steps: null
      warmup_ratio: 0.1
      last_epoch: -1
      # pytorch lightning args
      monitor: val_loss
      reduce_on_plateau: false
